### ISSUE TITLE
Fix mobile ad

### ISSUE THREAD

**Issue by kylepolich** [data-skeptic/dataskeptic.com#377]
When looking on a mobile phone, the Google Adsense banner is not a good fit (see below).

<img width="733" alt="screen shot 2018-01-17 at 3 14 55 pm" src="https://user-images.githubusercontent.com/1054674/35072438-7567e762-fb99-11e7-90c1-772e26758666.png">

How can we configure this component to take a more dynamic shape which is a better fit for this space?

**Comment by glozhkovoy** [comment]
I have investigated that issue.

I think it's because `responsive view` in the chrome isn't really responsive (in other words it's not really tell website that you're looking from the mobile realtime). I found that google adverts loads relative advertise on first load: that what happened on your example, you uploaded advertise on full version and after switched to the responsive mode.

Current dataskeptic.com on real iOS 
![img_e4de7d08d6bc-1](https://user-images.githubusercontent.com/20016615/35097219-eab15a3a-fc57-11e7-9e0f-c5d2be202a0d.jpeg)

The same on safari responsive mode
![screen shot 2018-01-18 at 1 58 16 pm](https://user-images.githubusercontent.com/20016615/35097242-fdda6192-fc57-11e7-8d9a-9c84556b9225.png)
