### ISSUE TITLE
How can it be done?

### ISSUE THREAD

**Issue by kylepolich** [data-skeptic/dataskeptic.com#535]
What if we wanted to give someone a javascript/html snippet to embed in their website.  The purpose of the embed would be to put our Chatbot on their page.

The embed should be required to provide a unique public token.  All requests should include the token, so that the server knows the exact source.

Can we make it as simple as it is to add Google Analytics to a page?

**Comment by gleblozhkovoy** [comment]
1. Dedicated websocket (https://socket.io/) server to handle messages and replies 
In my opinion handling messages locally is not scalable solution as it need to be. So I advice use web sockets instead of common REST API – it should be much faster.

2. Static server to serve assets (could be merged with ws-server) 
To speed up the chat bootstrap on separate page we need have a compiled (a.k.a) built chat version and serve asset files like icons, fonts, styles, e.t.c  

3. React chat in iframe
Technically to not broke the page and be sure chatbot works and looks like we expect (when you insert DOM elements [chatbot component] directly it can inherit styles from the `parent` page) we should put it in iframe (iframes could not provide errors for the parent page - f.e. if we use `new` react version and `host` use old one they will not conflict [in other words iframe separate from the page]).

After all this steps including chatbot will be simple as it is in GA. Just 
```<src="//server-url" type="text/javascript">var chatbotConfig = {.....```
