### ISSUE TITLE
Redux State Security/Performance/Possible errors Problem

### ISSUE THREAD

**Issue by gliblozhkovyi** [data-skeptic/dataskeptic.com#672]
I figured out that persisting entire Redux state in the Local Storage (https://github.com/data-skeptic/dataskeptic.com/blob/master/client/index.jsx#L102) could produce a lot of issues which are not visible yet.

Personally, I'm worrying regarding the security. Redux storage (not accessible at `prod` but saved at `localstorage`) may contain in the future some critical/personal user, DATAS, e.t.c information. 

Morover, storage item is updated after each redux update – so it reduce site performance. In other words, browser rewrites large JS object on almost any user action. That takes a lot of time. 

Also, it may have a lot of sides affects when we are updating store schemas.
That's why sometimes I update variable (https://github.com/data-skeptic/dataskeptic.com/blob/master/shared/reducers/SiteReducer.js#L10) to minimize the chance of errors.

So my suggestion is to decide which data we should memorize for the session. 

I see that now we need only a few things, not an entire state
- [  ] Player state
- [  ] Cart

**Comment by kylepolich** [comment]
@gliblozhkovyi I am glad you raised this.  Yet, I am not entirely clear on what the issue is.  I want to take privacy and security seriously, but I don't know how to evaluate the priority here.  Do you recommend we drop everything else and take care of this?  Are users exposed in any way?  Would you be upset if you were a user of our site?  How critical is this?  Also, how long is the effort to fix?
